os: linux
language: generic
dist: focal

jobs:
  include:
    - stage: create image
      name: "Job 1 – Create image"
      vm:
        create:
          name: test-same-name1

    - stage: create image
      name: "Job 2 – Create image"
      vm:
        create:
          name: test-same-name1
