os: linux
language: generic
dist: focal

jobs:
  include:
    - stage: create image
      name: "Job 1"
      vm:
        create:
          name: test-same-name1

    - stage: create image
      name: "Job 2"
      vm:
        create:
          name: test-same-name1
